### ISSUE TITLE
Upgrade your GitHub accout to "GitHub Pro" (for free)

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#1]
See https://education.github.com/benefits

**Comment by Lht97** [comment]
Dear Professor Zhang,

Thank you so much! I have clicked the address many times, but it always
shows me that there is a network error. I will try it later. Thank you
again.

Best Regards,
Haitian

**Comment by zaikunzhang** [comment]
Just search for GitHub education benefit.

I told this to the three of you a year ago. You are the only one who did not do it.

**Comment by Lht97** [comment]
Dear Professor Zhang,

I have tried many times, but it still shows like this. Maybe there is
something wrong with internet of school. I will try it later. Thanks so
much.

Best Regards,
Haitian

**Comment by zaikunzhang** [comment]
Everything works on my side in my office.
