### ISSUE TITLE
Correct the English in your comments!

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#10]
1. "Precondition" in the following line should be "Preconditions".

https://github.com/blockwise-direct-search/bds/blob/ced8cea6d68226f5d0ee1c997a15537e7c1269bf/src/blockwise_direct_search.m#L47

2. What is "pre-conditions"? Why ignore the obvious inconsistency? It should be "preconditions".

3. What does it mean to "operate" the preconditions? It should be "verify" or "check". 

5. conditionS IS?  

See https://en.wikipedia.org/wiki/Design_by_contract . 

Please, find someone to check each and every sentence of your comments. Make sure that the English is correct. Thank you very much.

**Comment by Lht97** [comment]
I have corrected the comments on verify_preconditions and verify_postconditions.
