### ISSUE TITLE
Make sure that the code works properly if `tol` is set to 0

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#12]
First of all, `tol` should be `alpha_tol`.

https://github.com/blockwise-direct-search/bds/blob/ced8cea6d68226f5d0ee1c997a15537e7c1269bf/src/blockwise_direct_search.m#L129

In most cases, "ABC" and "XYZ" should be the same when you have
```
ABC = options.XYZ
```

Secondly, please check whether the code works properly if this parameter is set to 0. If no, fix the code.

**Comment by zaikunzhang** [comment]
Let us use `StepTolerance` to be consistent with MATLAB. 

https://www.mathworks.com/help/optim/ug/optim.problemdef.optimizationproblem.optimoptions.html

You can write the following (which effectively violates the "In most cases" rule mentioned above): 
```
alpha_tol = options.StepTolerance;
```

**Comment by Lht97** [comment]
I have changed the name to StepTolerance, but I need to test whether our method works when tol = 0.
