### ISSUE TITLE
Decouple the update of the iterate and that of the step size; accept trial points with simple decreases

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#13]
Trust-region algorithms typically update the iterate and that of the step size in the following way. 

```
if reduction_ratio > eta_0
    iterate = trial_point; 
end
if reduction_ratio <= eta_1
    trust_region_radius = shrinking_factor * trust_region_radius;
else if reduction_ratio > eta_2
    trust_region_radius = expanding_factor * trust_region_radius; 
end
```

Here,  0 <= eta_0 <= eta_1 <= eta_2 <= 1, and 0 < eta_1 < 1. Typically values are eta_0 = 0, eta_1 = 0.1 ( should never be larger than 0.5), and eta_2 = 0.7. 

When eta_0 = 0, trial points with simple decreases are accepted, which is likely a good strategy in practice. 

Do the same for `bds`. 

The setting of `eta_1` and `eta_2` is tricky. You may try eps, 1.0E-10, 1.0E-9, ..., 1.0E-1, or any other values that you want to try, keeping eta_1<= eta_2. Find the best setting  (there are at least 50 possibilities).. 

Also, try what happens when eta_1 = 0. There is no theory for it even without blocks, but it does not hurt to try. 

Discuss with Cunxin @OptHuang and Tom @ragonneau if this is difficult. Make sure to ask them to check whether your implementation is correct.

**Comment by Lht97** [comment]
Thanks, Tom and Cunxin, I have implemented the above way of updating step size and accepting fval and xval.
