### ISSUE TITLE
Write a proper README

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#14]
The current README.md is not proper. Write a new one. It does not need to be long --- it can be just one sentence. Make sure to write it in correct and understandable English. 

Ask @OptHuang and @ragonneau for advice if needed.

**Comment by Lht97** [comment]
Thanks to Dr. Zhang, we already have a proper README of bds. I will write proper README for bds_slides and bds_articles as well.

**Comment by Lht97** [comment]
The latest version of README is ok, but I will update simultaneously if I introduce some new comparison or some theoretical analysis.
