### ISSUE TITLE
Write help information for each function

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#21]
This is a good example:

https://github.com/blockwise-direct-search/bds/blob/ced8cea6d68226f5d0ee1c997a15537e7c1269bf/src/blockwise_direct_search.m#LL2C1-L45C70

Each function should start with such information.

**Comment by Lht97** [comment]
In fact, I am writing comments of each function in the folder of src. As for the folder of competitors, I should also do this, and I will let competitors share the same subfunctions with bds.m. The same case for the folder of tests.

**Comment by Lht97** [comment]
I have written the help information of each function in the project and correct their spellings.
