### ISSUE TITLE
The roles played by `testbds_input` and `testbds` are strange

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#23]
You are using `testbds_input` to conduct the test (i.e., to plot the profiles), and `testbds` is only a private function called by `testbds_input`. The logic is strange. 

The roles of  `testbds_input` and `testbds` should be exchanged. `testbds` should be the function that performs the test, and it calls `testbds_input` to get the parameters / options; `testbds_input.m` should be placed under `private`. 

1. Please rename `testbds` to `profile_bds`, and  `testbds_intput` to `get_profile_options`. Modify them so that the former can be put under `tests` and the latter under `private`. 

2. Please rename `options_solvers` to `solver_options` and `options_test` to `test_options`. 

Ask Cunxin @OptHuang for help if the logic is not clear to you.

**Comment by Lht97** [comment]
I have changed the name of the files above correctly.

**Comment by Lht97** [comment]
I have changed the names of the files above correctly.
