### ISSUE TITLE
The way you handle the paths is strange

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#24]
Take https://github.com/blockwise-direct-search/bds/blob/main/tests/testbds_input.m as an example. You are doing the following.

1. In line 8, you restore the default paths, which is good. 
2. Between lines 15 and 37, you add paths needed for the test, which is fine. 
3. In lines 250--255, you remove the added paths, which is correct. 

However, you forget to restore the path to the state before the test. What you should do is the following.  

1. Record the current paths.
2. Restore the default paths. 
3. Add the paths needed. 
4. Restore the paths recorded in 1. 

See the following for an example. 
https://github.com/libprima/prima/blob/main/matlab/tests/profile.m

Discuss with Cunxin @OptHuang about this if it is not clear to you.

**Comment by Lht97** [comment]
I have implemented the above things in
https://github.com/blockwise-direct-search/bds/blob/main/tests/profile.m
