### ISSUE TITLE
Change `preconditions` to `verify_preconditions`; similar for `postconditions`

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#26]
https://github.com/blockwise-direct-search/bds/blob/8388b2d34650557ba50dce454170b03c979db0fe/src/bds.m#L52

1. Change the name of the function.
2. English: "preconditions IS"?
3. Read the previous issues carefully, including the comments I wrote below. Check them one by one to make sure that you have addressed them correctly. Both 1 and 2 were mentioned in previous issues:
https://github.com/blockwise-direct-search/bds/issues/9
https://github.com/blockwise-direct-search/bds/issues/10
5. If you believe you have solved the problem corresponding to an issue, then add a comment about your solution and close the issue. I will then check them.

**Comment by Lht97** [comment]
I have changed them to verify_preconditions and verify_postconditions.
