### ISSUE TITLE
Compare BDS with NOMAD

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#27]
See

https://www.gerad.ca/en/software/nomad/

This is a famous state-of-the-art DFO package. It is quite versatile. Here, we only test BDS and NOMAD on unconstrained problems (and bound-constrained ones in the future).

**Comment by zaikunzhang** [comment]
Tom @ragonneau and Cunxin @OptHuang should also pay attention to NOMAD.

**Comment by Lht97** [comment]
I have got the comparing results on s2mpj (https://github.com/GrattonToint/S2MPJ) problem set.
