### ISSUE TITLE
Add parentheses

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#28]
https://github.com/blockwise-direct-search/bds/blob/93121ff9fc188932ddb6b443110fc141fe0f8e5f/src/private/inner_direct_search.m#LL99C27-L99C27

There is no mistake, but it is better to write
```
    sufficient_decrease = (fnew + sufficient_decrease_factor * alpha^2/2 < fbase);
```

**Comment by Lht97** [comment]
I have added parentheses.
