### ISSUE TITLE
Rewrite this condition

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#30]
https://github.com/blockwise-direct-search/bds/blob/93121ff9fc188932ddb6b443110fc141fe0f8e5f/src/private/inner_direct_search.m#LL104C1-L105C1

I think 
```
    if (options.accept_simple_decrease && fnew < fval) || sufficient_decrease
```
works better than
```
    if (options.accept_simple_decrease || sufficient_decrease) && fnew < fval
```
They are equivalent. Why?

**Comment by Lht97** [comment]
Dear Professor Zhang,

For me, they might not be the same. If options.accept_simple_decrease =
true, sufficient decrease = true and fnew>= fval. Since a point satisfying
sufficient decrease does not mean it is smaller than fval.

Best Regards,
Haitian

**Comment by zaikunzhang** [comment]
I see. You are not wrong in principle. However, in the current implementation of BDS, `fbase` is updated to `fval` before the code enters any block. See 

https://github.com/blockwise-direct-search/bds/blob/93121ff9fc188932ddb6b443110fc141fe0f8e5f/src/bds.m#L254-L255

Indeed, (`fbase`, `xbase`) is not needed at all, because it is always identical to (`fval`, `xval`).  `fbase` and `xbase` should be deleted.  

Tell me if I have overlooked something. Thanks.

**Comment by Lht97** [comment]
Dear Professor Zhang,

Thanks for your reply!  In our implementation, fbase is never changed
during inner_direct_search.m even if fval is changed during
inner_direct_search.m. So there is still chance that sufficient decrease is
true and fnew>= fval.

Best Regards,
Haitian

**Comment by zaikunzhang** [comment]
I see. What you said can happen if the inner direct search does complete polling. If it does opportunistic polling, then `fnew >= fval` cannot happen when `sufficient_decrease` if true. Is this correct?

However, you do not need to pass both `[fval, xval]` and `[fbase, xbase]` to the inner direct search, because they are always identical at the entry of the inner direct search. `[fbase, xbase]` should be a local variable within the inner direct search. It should not exist in the main function. Is this correct?

**Comment by Lht97** [comment]
Dear Professor Zhang,

You are right. When considering opportunistic polling, fval and xval is
enough. Thanks for your reply.

Best Regards,
Haitian

**Comment by zaikunzhang** [comment]
> However, you do not need to pass both `[fval, xval]` and `[fbase, xbase]` to the inner direct search, because they are always identical at the entry of the inner direct search. `[fbase, xbase]` should be a local variable within the inner direct search. It should not exist in the main function. Is this correct?

What about this?

**Comment by Lht97** [comment]
Dear Professor Zhang,

In complete polling, fval may not equal to fbase in the inner direct search.

Best Regards,
Haitian

**Comment by zaikunzhang** [comment]
You did not understand my comment. Ask Cunxin @OptHuang  for help. Thanks.

**Comment by Lht97** [comment]
Dear Professor Zhang,

Sorry for my reply before. I have figured out what you mean by myself. In
fact, fbase is fval before entering this block, so it should be defined in
the inner direct search and we do not need to pass it into inner direct
search.

Best Regards,
Haitian

**Comment by zaikunzhang** [comment]
> I see. What you said can happen if the inner direct search does complete polling. If it does opportunistic polling, then `fnew >= fval` cannot happen when `sufficient_decrease` if true. Is this correct?

Please write some comments about this fact. @Lht97
