### ISSUE TITLE
This is wrong

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#33]
https://github.com/blockwise-direct-search/bds/blob/463c431e5351d7f0785323127a88acac1779c4d9/src/private/inner_direct_search.m#L115-L117C1

You did not understand my previous comment https://github.com/blockwise-direct-search/bds/issues/29 . 

It should not be difficult. Think about it. If you cannot figure it out, ask Cunxin @OptHuang for help.

**Comment by Lht97** [comment]
I have written the correct comment in inner_direct_search.m.
