### ISSUE TITLE
Implement and test SBDS and RBDS

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#36]
See https://github.com/blockwise-direct-search/paper/wiki/Overview for their definitions. They are easy to implement based on the current code. (Indeed, SBDS has been implemented, corresponding to your `Randomized_array`, but the code has to be revised, which I will explain in another issue.)

Please add the following options related to SBDS and RBDS. 

1. `Algorithm` (with a capital A, to be consistent with MATLAB) : `cbds`, `gsds` (synonym of `cbds`), `sbds`, `rbds`. 
2. `shuffling_period`:  a positive integer, default: 1. This is only used for SBDS, which shuffles the blocks every `shuffling_period` iterations.
3. `replacement_delay`: an integer between 0 and nb - 1,  default: 0. This is only used for RBDS. Suppose that `replacement_delay` is $r$. If block $i$ is selected at iteration $k$, then it will not be selected at iterations $k+1$, ..., $k+r$.

**Comment by Lht97** [comment]
Find a better way to implement.
