### ISSUE TITLE
Remove unused variables or functions!!!

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#37]
1. Where is `nb_visited` used?
https://github.com/blockwise-direct-search/bds/blob/b4b09d620703d6f54a87df5c18ecee3edaae46e5/src/bds.m#L216

2. Where is `hist` used??

https://github.com/blockwise-direct-search/bds/blob/b4b09d620703d6f54a87df5c18ecee3edaae46e5/src/bds.m#L194

3. Where is `options.permutation_indicator` used???
 
https://github.com/blockwise-direct-search/bds/blob/b4b09d620703d6f54a87df5c18ecee3edaae46e5/src/bds.m#L232

NOTE: These are only a few EXAMPLES rather than an exhaustive list. 

Please, please, please, check your code carefully and thoroughly, and remove unused variables or functions. 

I beg you. Please, help me. Please, help us. 

Thank you very much.

**Comment by Lht97** [comment]
I have removed the unused variables that you mentioned above, and I am working on finding all of them.
