### ISSUE TITLE
The implementation of SBDS

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#38]
I do not think the implementation below is good. The function `permutation` is unnecessary. 
https://github.com/blockwise-direct-search/bds/blob/b4b09d620703d6f54a87df5c18ecee3edaae46e5/src/bds.m#LL231C1-L232C1

I suggest changing 
```
    block_indices = permutation(block_indices, options);
```
to 
```
if strcmpi(Algorithm, "sbds") && mod(iter - 1, shuffle_period) == 0   % @Lht97 Why iter - 1 rather than iter?
    % Make sure that `shuffle_period` is defined when `Algorithm` is "sbds".
    block_indices = randperm(nb);
end
```
Then remove `permutation.m`.

**Comment by Lht97** [comment]
I have implemented SBDS in bds.m without permutation.m.
