### ISSUE TITLE
Why is the repository so large?

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#39]
Check why and how to reduce the size. For this, you need the help of Tom @ragonneau . Thank Tom.

**Comment by zaikunzhang** [comment]
In case you do not see what I mean: the size of this repo is more than 250 MB. Normally, a repo like this should be less than 5 MB.

**Comment by ragonneau** [comment]
Hi @zaikunzhang,

We worked on that matter today with @Lht97. In the early stages of this project, the matcutest_compiled repo was manually added to the bds repo (not as a submodule, but by copying the files directly). Even if these files are no longer present in recent commits, they were still part of the repo's history.

To solve this issue, we removed the matcutest_compiled archives from the history. Checking out commits for which these files were present might now fail, but I could not see any better solution. The complete repo is now 6.65MB.

Cheers,
Tom.

**Comment by zaikunzhang** [comment]
Great! Thank you!
