### ISSUE TITLE
"permutate" is not a valid English word

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#4]
"permutate" does not exist in English. Check Oxford/Cambridge/Longman dictionaries. The correct one is "permute". 

However, the function name `permutate` should not be changed to `permute`. Why?

**Comment by Lht97** [comment]
Dear Professor Zhang,

Thanks for your advice. In my opinion, it should be modified as permutation.

Best Regards,
Haitian

**Comment by zaikunzhang** [comment]
OK
