### ISSUE TITLE
Let us use lower cases for the names of algorithms within the code

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#44]
https://github.com/blockwise-direct-search/bds/blob/85ad91015f809cb69a354e3555a382ed2860f94e/src/bds.m#L226

**Within the code of BDS**, let us use lower cases for the names of algorithms (CBDS, SBDS, RBDS, PBDS, ...). 

When you need to identify the algorithm using the name, do the following.

1. `strcmpi(Algorithm, "cbds")` checks whether `Algorithm` is "cbds", case-insensitively. 
2. If you use a switch, do the following.
```
switch lower(Algorithm)
    case {"cbds"}
    ...
    case {"sbds"}
    ...
end
```

**Comment by Lht97** [comment]
I have changed the names of algorithms in bds.m to lower cases and I allow users to input upper cases.
