### ISSUE TITLE
Correct the English

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#45]
https://github.com/blockwise-direct-search/bds/blob/85ad91015f809cb69a354e3555a382ed2860f94e/src/private/inner_direct_search.m#L117-L119

In terms of grammar, "there is some case where" should be "there are some cases where". However, logically, it does not work. It should be "there may be cases where", or better, "it may happen that". 

"as long as ..., then" does not work.

**Comment by Lht97** [comment]
115th line on inner_direct_search.m

**Comment by Lht97** [comment]
Explain the situations more specifically. Use the comment above to describe the situations.

**Comment by Lht97** [comment]
I have modified the comment of https://github.com/blockwise-direct-search/bds/blob/00e99a8454ad3a0bf0facb078128b117cd33925a/src/private/inner_direct_search.m#L140.
