### ISSUE TITLE
This comment is wrong

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#46]
https://github.com/blockwise-direct-search/bds/blob/24d1f73344a5c889a2d24487ec19faf98c38f57e/src/bds.m#LL227C1-L228C1

**Comment by Lht97** [comment]
I have corrected the comment (https://github.com/blockwise-direct-search/bds/blob/00e99a8454ad3a0bf0facb078128b117cd33925a/src/bds.m#L324)
