### ISSUE TITLE
This files is not needed anymore

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#48]
https://github.com/blockwise-direct-search/bds/blob/f103771bebbf473d3627d3f581a74e380ce37250/src/private/permutation.m#L1-L32

Again, please, please, please, remove the unused variables, functions, files, ... I beg you, please do it.

**Comment by zaikunzhang** [comment]
@OptHuang Cunxin, could you help me to check why this is so difficult to do, and help Haitian to do it? Thanks.

**Comment by Lht97** [comment]
I have deleted this file.
