### ISSUE TITLE
This  comment is wrong

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#49]
https://github.com/blockwise-direct-search/bds/blob/f103771bebbf473d3627d3f581a74e380ce37250/src/bds.m#L227

Have you checked this? It is still wrong. Ask Cunxin or Tom for help, please.

**Comment by zaikunzhang** [comment]
https://github.com/blockwise-direct-search/bds/blob/618022a84b64acfaa0452dce073c64b2630e7c07/src/bds.m#L232

This is still wrong. Ask someone for help if you cannot figure it out.

**Comment by Lht97** [comment]
I have already changed the comment on why iter-1 by (https://github.com/blockwise-direct-search/bds/blob/00e99a8454ad3a0bf0facb078128b117cd33925a/src/bds.m#L324)
