### ISSUE TITLE
DS and DSPD should not be implemented separately, because both are special cases of BDS

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#51]
1. DS is a special case of BDS with only one block. 

2. DSPD is a special case of BDS with only one block, and the searching direction set is chosen randomly. 

Both of them can be obtained from the existing implementation of BDS by setting some options. 

(It is also the case for RBDS.)

**Comment by Lht97** [comment]
I have made DS and DSPD work under the framework of bds.m. I need to make RBDS as well.

**Comment by Lht97** [comment]
I have made RBDS work under the framework of BDS.

**Comment by Lht97** [comment]
I have implemented DSPD separately by (https://github.com/blockwise-direct-search/bds/blob/main/tests/competitors/dspd.m)  and implemented RBDS under the framework of BDS.
