### ISSUE TITLE
Test what happens when the starting point is bad

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#52]
Use the following code to generate the starting point, and test the performance of different algorithms. 

```
r = randn(n,1);
r = r / norm(r);
x0 = p.x0 + 10 * max(1, norm(x0)) * r;
```

The same as tests with noise, make sure the following.

1. Conduct a few random experiments and take the average of the performance profiles.
2. For each random experiment, different solvers receive the same starting point.

**Comment by Lht97** [comment]
I have tested locally, and I will close this issue until it works on GitHub actions.

**Comment by zaikunzhang** [comment]
> I have tested locally, and I will close this issue until it works on GitHub actions.

Your answer should be "I have tested it. I observed the following. ...." 

Your current answer does not contain any information.

**Comment by zaikunzhang** [comment]
> I have tested locally, and I will close this issue until it works on GitHub actions.

Your answer should be "I have tested it. I observed the following. ...." 

Your current answer does not contain any information.
