### ISSUE TITLE
Change names of the algorithms

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#53]
Use the following names:

CBDS for Cyclic Blockwise Direct Search (i.e., Gauss-Seidel Direct Search)
PBDS for (Randomly) Permuted Blockwise Direct Search 
JDS for Parallel Blockwise Direct Search or Jacobi Direct Search (not discussed for the moment)

See: 
https://github.com/blockwise-direct-search/paper/wiki/Overview

This should be done before the confirmation.

**Comment by zaikunzhang** [comment]
The names are decided according to existing block coordinate descent methods, e.g.,

https://jmlr.csail.mit.edu/papers/volume18/17-157/17-157.pdf

**Comment by Lht97** [comment]
I have changed them and implement them under the framework of BDS.
