### ISSUE TITLE
Compare BDS with NEWUOA, BOBYQA, and COBYLA interfaced by NLopt

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#57]
To make sure that the comparison against NEWUOA/BOBYQA/COBYLA is not due to hidden bugs in PRIMA, please compare with NEWUOA, BOBYQA, and COBYLA interfaced by [NLopt](https://github.com/stevengj/nlopt). As far as I know, NLopt does not contain UOBYQA or LINCOA (tell me if I am wrong). 

1. If you need help with the installation and usage of NLopt, please check [its documentation](https://nlopt.readthedocs.io/en/latest/NLopt_Matlab_Reference/). Discuss it with Tom @ragonneau and Cunxin @OptHuang if necessary. 

2. I expect that PRIMA works better than NLopt (you should check whether this is true or not in your tests). Therefore, the comparison with NLopt should be more favorable to BDS. Tell me what you observe. 

There are comparisons with other solvers (NOMAD etc). Do not forget them. 

Thanks.

**Comment by Lht97** [comment]
I have implemented the comparsion between BDS and NLopt.
