### ISSUE TITLE
The implementation of DSPD is wrong

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#58]
https://github.com/blockwise-direct-search/bds/blob/893667e4590d91c068225a98dfabc862c01705d9/src/bds.m#L279-L290

This part is (still) wrong. 

@OptHuang You should know this algorithm well enough to implement it correctly.

**Comment by OptHuang** [comment]
Dear Prof. Zhang,

Thanks for your reminder. First, now I know what is wrong after reading Haitian's comments and I will tell Haitian how to modify it. Second, today we two only checked and corrected comments in "src" for 3.5 hrs. Thank you again.

Best regards,
Cunxin

**Comment by zaikunzhang** [comment]
First things first: **MATLAB does not support loops (just imagine it in that way). Any loop is wrong.** A MATLAB programmer should always keep this in mind. This applies to any **scripting language** (check what this means), including Python. Understand? 

However, this is **not** the major mistake of the current implementation.

**Comment by OptHuang** [comment]
Yes, you are right. Noted with thanks.

> First things first: **MATLAB does not support loops (just imagine it in that way). Any loop is wrong.** A MATLAB programmer should always keep this in mind. This applies to any **scripting language** (check what this means), including Python. Understand?
> 
> However, this is **not** the major mistake of the current implementation.

**Comment by Lht97** [comment]
Thanks to Dr. Zhang and Cunxin, I have corrected the way of obtaining the searching set in DSPD correctly by
https://github.com/blockwise-direct-search/bds/blob/e7bf674ecda6790e7051808840688cb03f8306c9/tests/competitors/dspd.m#L224

**Comment by Lht97** [comment]
I have implemented DSPD separately and correctly under the discussion of Cunxin and Dr. Zhang.
