### ISSUE TITLE
Implement DSPD separately

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#59]
https://github.com/blockwise-direct-search/bds/blob/7efe2255c870f13b421ac696497fdb601382dc7a/src/bds.m#L288-L303

**A.** This part does not fit the flow of BDS. DSPD should be implemented separately (my fault). 

1. Implement it as dspd.m. Put it under `tests/competitors`. 
2. Make sure to call https://github.com/blockwise-direct-search/bds/blob/main/src/private/inner_direct_search.m in DSPD.
3. Remember to revise bds.m and files below `src/private` VERY CAREFULLY after DSPD is removed from it: anything about DSPD should be removed. Consequently, many things may be simplified. Understand? If you do not understand what I am talking about, ask me. 

**B.** The logic below concerning `m == 2` is wrong. 

https://github.com/blockwise-direct-search/bds/blob/7efe2255c870f13b421ac696497fdb601382dc7a/src/bds.m#L104-L113 
https://github.com/blockwise-direct-search/bds/blob/7efe2255c870f13b421ac696497fdb601382dc7a/src/bds.m#L288-L303

The correct logic should be the following:
1. If `num_random_vectors` is not present and $p_0 \le 1/2$ (you know what $p_0$ means), then set $D = [-r, r]$. 
2. Otherwise, set `m` and `D` as you did. 

**C.**  More seriously, 
1. DSPD does not accept `D` as an input, and hence `m = size(D, 2);` does not make sense. 
2. What is the following? It is wrong in **SO MANY WAYS**. Undrerstand? If no, make sure to ask.  
```
            for i = 1:m
                D = random("norm", 0, 1, n, m);
                % Normalize D.
                D = normc(D);
            end
```

**Comment by zaikunzhang** [comment]
PLEASE READ THE ABOVE COMMENTS VERY CAREFULLY AND ADDRESS EACH POINT OF THEM. Thanks. @OptHuang @Lht97

**Comment by Lht97** [comment]
A. I have implemented DSPD by https://github.com/blockwise-direct-search/bds/blob/main/tests/competitors/dspd.m; since DSPD needs to select the searching set every iteration, which is not suitable for the framework of BDS.
B. I use https://github.com/blockwise-direct-search/bds/blob/e7bf674ecda6790e7051808840688cb03f8306c9/tests/competitors/dspd.m#L224 to decide the searching set for every iteration
C. The comment is the same as B.

**Comment by Lht97** [comment]
I have implemented DSPD separately and correctly under the discussion of Cunxin and Dr. Zhang.
