### ISSUE TITLE
The structure of this folder is wrong

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#60]
https://github.com/blockwise-direct-search/bds/tree/7efe2255c870f13b421ac696497fdb601382dc7a/tests/competitors

1. Any competitor should correspond to a `.m` file under `tests/competitors` directly. This `.m` file may be the competitor itself, or may be a wrapper that fits the needs of our testing. Do not put this `.m` file in subdirectories, although it may rely on other `.m` files from certain subdirectories. For example, `wm_newuoa.m` (see below) will rely on files from a subdirectory `wm_newuoa`. (如果看不懂请问我！ )
4. Why is `rbds.m` here?
5. What is `bds_polling.m`?  
6. Change `mnewuoa_wrapper` to `wm_newnuoa`, which means Wild and More's implementation of NEWUOA. BTW, where did you use it???

**Comment by Lht97** [comment]
1. Thanks Dr. Zhang. I have understood what you mean and I want to make sure that whether different competitors can share the same private folder or not.
2. There is no use of rbds.m. I have deleted it.
3. bds_polling.m is the version that I did before. cbds is one special case of it so I keep it here for future research.
4. I have renamed mnewuoa_wrapper as wm_newuoa. Thanks for your reminding.
