### ISSUE TITLE
How do you maintain the consistency of the functions under these two directories?

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#61]
These two directories share many critical functions (e.g., inner_direct_search.m). How do you make sure that they are consistent???

https://github.com/blockwise-direct-search/bds/tree/main/tests/competitors/private
https://github.com/blockwise-direct-search/bds/tree/main/src/private

**Comment by Lht97** [comment]
I have used the symbolic link to make sure different solvers will share the same private functions.
