### ISSUE TITLE
Please improve the examples

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#62]
https://github.com/blockwise-direct-search/bds/tree/main/examples

Currently, nothings here is a proper example. Ask Tom how to do it, or simply check 

https://github.com/libprima/prima/tree/main/matlab/examples

**Comment by Lht97** [comment]
Thanks for Dr. Zhang's advice. Now the example is shown like
https://github.com/blockwise-direct-search/bds/blob/main/examples/rosenbrock_example.m
