### ISSUE TITLE
with_cycling_memory

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#63]
https://github.com/blockwise-direct-search/bds/blob/7efe2255c870f13b421ac696497fdb601382dc7a/src/bds.m#L24C10-L24C10

**Comment by Lht97** [comment]
I have used "find . -type f -exec sed -i 's/with_memory/with_cycling_memory/g' {} +" to relace "with_memory" with "with_cycling_memory".
