### ISSUE TITLE
Explain this line better and move it downward

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#64]
https://github.com/blockwise-direct-search/bds/blob/7efe2255c870f13b421ac696497fdb601382dc7a/src/bds.m#L353

Please tell the user/reader why we cycle the indices at 
https://github.com/blockwise-direct-search/bds/blob/7efe2255c870f13b421ac696497fdb601382dc7a/src/private/inner_direct_search.m#L126-L131
and why we need to "Retrieve the order of the polling directions" at 
https://github.com/blockwise-direct-search/bds/blob/7efe2255c870f13b421ac696497fdb601382dc7a/src/bds.m#L351-L353

In addition, it is better to move 
```
        searching_set_indices{i_real} = suboutput.direction_indices;
``` 
downward (below the current line 369).

**Comment by Lht97** [comment]
I have explained why we cycle the indices here by https://github.com/blockwise-direct-search/bds/blob/ba702172f9608a3d2f9f3349740f748bcdf7fb9f/src/private/inner_direct_search.m#L152 and adjusting the searching set at https://github.com/blockwise-direct-search/bds/blob/55fb596ef0cda564591fe2f44e2123285a093f2b/src/bds.m#L421
