### ISSUE TITLE
This is strange and probably wrong

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#65]
https://github.com/blockwise-direct-search/bds/blob/fa37772ab6a23f94a1fc320c0eff2033b29d9d2b/tests/run_tough.m#L32-L35

The three lines are composed in a strange way and are probably wrong. 

In addition, what do you mean by "crash"? Who caused the crash?

**Comment by Lht97** [comment]
I have tested those problems on each solver to see whether it takes long time to solver, which is commented as
(https://github.com/blockwise-direct-search/bds/blob/5955d231c9e1bbbd54e47848c67aff4aeb798fb9/tests/profile.m#L70)
