### ISSUE TITLE
Write a `setup.m`

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#67]
This is a function for the user to set up the package. It should do two things:
- `setup`  --- install the package. Basically, add and save the path.
- `setup uninstall` ---- uninstall the package. Basically, remove the saved path, and tell the user that he/she can remove the delete the package. 

See https://github.com/libprima/prima/blob/main/setup.m for an example. Note that the `setup.m` for BDS should be **much simpler**, because there is no compilation, and because there is only one solver. 

- For how to add and save the path, see 
https://github.com/primalib/prima/blob/07a9bc826ffcdd60770dc59bb1ec3282237542e4/setup.m#L243-L316
You can almost copy it. **BTW, for any major code copied from PRIMA or any other open-source project, please mention it clearly in the help information.** You cannot claim that you are the author of such code.

- For how to uninstall the package, see 
https://github.com/primalib/prima/blob/07a9bc826ffcdd60770dc59bb1ec3282237542e4/matlab/setup_tools/uninstall_prima.m
You need to simplify it. 

Since your case is simple, you may put all functions in one file (i.e., `setup.m`). 

After doing this, you should not manually add `bds/src/` to your path in any test anymore. Instead, you should call `setup`. 

Please first implement this yourself. Discuss with Cunxin if needed. Finally, ask Tom to help you to verify it. 

Believe me, it is quite easy to implement!

**Comment by Lht97** [comment]
Thanks for your advice. I have written a setup.m and make some tools for setup.m integrated into setup.m.
