### ISSUE TITLE
Stress test

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#68]
https://github.com/blockwise-direct-search/bds/blob/72a84e04aa1208f3efca9e371331cece0ce300ee/.github/workflows/tough_test.yml#L71

This file should be named "stree_test.yml". The description is "Stress test" rather than "Tough test"

Also, why do you need "Optimization Toolbox"?

**Comment by Lht97** [comment]
Thanks Dr. Zhang's advice. I have renamed the file. For "Optimization Toolbox", when I need to induce fminunc as competitor, I have to introduce this toolbox.
