### ISSUE TITLE
https://github.com/blockwise-direct-search/bds/actions/runs/6094680059/job/16536703785#step:11:27

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#69]
@Lht97 Please check lines 25--30 of the following log:

https://github.com/blockwise-direct-search/bds/actions/runs/6094680059/job/16536703785#step:11:27

It says 
```
  [Warning: Name is nonexistent or not a directory:
  /home/runner/work/bds_new_framework/bds_new_framework/prima/matlab/interfaces] 
  [Warning: Name is nonexistent or not a directory:
  /home/runner/work/bds_new_framework/bds_new_framework/prima/matlab/setup_tools] 
  [Warning: Name is nonexistent or not a directory:
  /home/runner/.local/matcutest/mtools/src] 
```

What does this mean? What is wrong here? Please fix it. 

You should be able to solve the problem yourself. Ask others for help if needed.

**Comment by Lht97** [comment]
For stress test, we do not need to use matcutest and prima. I have removed the installation step of those two packages. Now there do not exist such kinds of warning.
