### ISSUE TITLE
Remove / revise unnecessary options 

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#7]
1. `memory` should be `with_memory`. 
2. Is `memory` still needed? Where and how?
3. Is `cycling_outer` still needed? Where and how? 

Check other options as well.

**Comment by Lht97** [comment]
Dear Professor Zhang,

Memory and cycling_outer are still needed for the competitors (like
bds_polling).

Best Regards,
Haitian

**Comment by zaikunzhang** [comment]
If they are only needed by the competitors, then they should not appear under the directory `src` but under `test`. 

Check all the options, not only these two.

**Comment by Lht97** [comment]
Change `with_memory` to `with_cycling_memory`.

**Comment by Lht97** [comment]
I have used symbolic link to make sure the competitors and BDS will use the same options. Besides, I have changed memory to with_cycling_memory.
