### ISSUE TITLE
Correct these in https://github.com/blockwise-direct-search/bds/blob/main/.github/workflows/profile_small_sdl.yml

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#74]
1. profile_small_sdl -> profile_small_sd
2. Do not use "sufficient decrease level". Use "sufficient decrease factor"
3. Do not use high, medium, low ... They do not make sense in this context. Use specific values like 0, eps, 1.0e-15, ...
4. Do not copy from others without asking why. 

@Lht97 Handle this before 12:00 noon 12 September, write comments about how you did it, and close the issue.

**Comment by Lht97** [comment]
1. I directly changed the name of the file.
2. Use some code like find . -type f -exec sed -i 's/sufficient_decrease_level/sufficient_decrease_factor/g' {} \; and grep -r -l "sufficient_decrease_level" to check whether all of them are replaced.
3. I just passed the values to the algorithm directly and use some code like num2str to convert it into string in legend, stamp and pdfname.
