### ISSUE TITLE
Make the output of `xhist` optional

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#76]
`xhist` takes much memory when the problem is large. Add an option `output_xhist` to indicate whether to output `xhist`. Default it to `false`. 

In the [stress test](https://github.com/blockwise-direct-search/bds/blob/main/tests/stress.m), **set `options.output_xhist` to `true` as long as the runner can afford it**. Otherwise, set it to `false`. **You need to try it before setting it.** Ask @OptHuang Cunxin if you do not understand what I am talking about. 

Thanks.

**Comment by zaikunzhang** [comment]
> xhist takes much memory when the problem is large. Add an option output_xhist to indicate whether to output xhist. Default it to false.

This means that the user will input an option `output_xhist`. Then you do the following.
- If `output_xhist = false`, do nothing
- If `output_xhist = true`, and the arrays are not too big, then output `xhist`.
- If `output_xhist = true`, but the arrays are too big, then raise a warning, and set `output_xhist = false`.  

In the third case, there are more reasonable choices, but let us keep things simple for the moment ---anyway, in the problems we target, this case will very unlikely occur. 

Thanks. @Lht97 @OptHuang

**Comment by Lht97** [comment]
I have set output_xhist and output_alpha_hist as options for (https://github.com/blockwise-direct-search/bds/blob/main/src/bds.m)
