### ISSUE TITLE
Many tests are repetitive or do not make sense

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#77]
Haitian @Lht97 ,

Many tests here are repetitive or do not make sense:

https://github.com/blockwise-direct-search/bds/actions/runs/6208282715/workflow

Please remove the unnecesary ones. This is very important. Otherwise, you cannot understant the results of the experiements, and neither others. 

Cunxin @OptHuang , please help Haitian to fix this before 18:00 Monday 18 September 2023 and report to me. 

Thanks.

Zaikun

**Comment by zaikunzhang** [comment]
BTW, this will not take more than 15 minutes to fix. Thanks.

**Comment by zaikunzhang** [comment]
Let me be more explicit. Please only test the following:

[plain, noise_1e-1, noise_1e-3, noise_1e-5, noise_1e-7, randomx0_1e-3, randomx0_1e1]

- plain: everything is plain, no noise, no perturbation in x0
- noise_xx: obvious
- randomx0_yy: obvious

Thanks. @Lht97 @OptHuang

**Comment by zaikunzhang** [comment]
> randomx0_1e1

Note that 1e1 = 10. @Lht97 @OptHuang

**Comment by Lht97** [comment]
Thanks for your advice. Now, there are seven situations to test:
https://github.com/blockwise-direct-search/bds/blob/00e99a8454ad3a0bf0facb078128b117cd33925a/.github/workflows/profile_pbds_big.yml#L27
