### ISSUE TITLE
Implement recursive and parallel tests

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#78]
Recursive test: whether the solver works properly when invoked recursively. For example
https://github.com/libprima/prima/blob/main/matlab/tests/recursive.m

Parallel test: whether the solver works properly when invoked in parallel. For example
https://github.com/libprima/prima/blob/main/matlab/tests/parallel.m

**Comment by Lht97** [comment]
Thanks for your advice. I have implemented them with https://github.com/blockwise-direct-search/bds/blob/main/.github/workflows/parallel_test_matlab.yml and https://github.com/blockwise-direct-search/bds/blob/main/.github/workflows/recursive_test_matlab.yml respectively.
