### ISSUE TITLE
How did you decide the earliest version of MATLAB that is supported?

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#79]
https://github.com/blockwise-direct-search/bds/blob/edfd73cb678fb1c8336eb745ea8c72f37f91531d/setup.m#L34-L37

**Comment by Lht97** [comment]
Since I use vecnorm function in https://github.com/blockwise-direct-search/bds/blob/00e99a8454ad3a0bf0facb078128b117cd33925a/src/private/get_searching_set.m#L78, which appeared in since MATLAB 2017b.
