### ISSUE TITLE
What do these two cases mean?

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#80]
https://github.com/blockwise-direct-search/bds/blob/edfd73cb678fb1c8336eb745ea8c72f37f91531d/setup.m#L81-L85

**Comment by Lht97** [comment]
If user input `setup bds`, only src folder is added to the path. If user input `setup`, all the directories in BDS are added to the path.

**Comment by Lht97** [comment]
After discussing with Cunxin and Tom, there only exists one case that user can input setup to add the path.
