### ISSUE TITLE
I do not understand these files

### ISSUE THREAD

**Issue by zaikunzhang** [blockwise-direct-search/bds#82]
I think something is seriously wrong with the following files. Otherwise, they should not exist at all.  

https://github.com/blockwise-direct-search/bds/blob/main/tests/competitors/matlab_fminsearch.m
https://github.com/blockwise-direct-search/bds/blob/main/tests/competitors/matlab_fminunc.m

In particular, where and how did you set `options` for these solvers? Don't you need to translate the options so that the solvers understand them correctly? 

Similar questions should be asked about the following file:

https://github.com/blockwise-direct-search/bds/blob/main/tests/competitors/matlab_patternsearch.m

This makes me doubt the correctness of all comparisons involving these three solvers --- and I am also worried about other solvers. 

If you do not understand what I am talking about, ask @Tom or @Cunxin.

**Comment by Lht97** [comment]
I have removed those files and use fminsearch and fminunc directly. But for my understanding, those files can be regarded as wrappers. I will check the difference between these two situations. Thanks for your advice.

**Comment by Lht97** [comment]
I have made every competitor has its own wrapper to deal with the common options.
